
CREATE TABLE localizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zona VARCHAR(255) NOT NULL,
    data_hora TIMESTAMP
);


CREATE TABLE moto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificador VARCHAR(255) UNIQUE NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    placa VARCHAR(255) NOT NULL,
    ativa BOOLEAN DEFAULT TRUE,
    localizacao_id BIGINT,
    CONSTRAINT fk_moto_localizacao FOREIGN KEY (localizacao_id) REFERENCES localizacao(id)
);