CREATE TABLE MOTO (
    id SERIAL PRIMARY KEY,
    identificador VARCHAR(255) NOT NULL UNIQUE,
    modelo VARCHAR(255) NOT NULL,
    placa VARCHAR(255) NOT NULL,
    ativa BOOLEAN DEFAULT TRUE NOT NULL
);