CREATE TABLE LOCALIZACAO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    zona VARCHAR(255) NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    moto_id BIGINT,
    CONSTRAINT fk_moto FOREIGN KEY (moto_id) REFERENCES MOTO(id)
);