CREATE TABLE LOCALIZACAO (
    id SERIAL PRIMARY KEY,
    zona VARCHAR(255) NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    moto_id BIGINT,
    CONSTRAINT fk_moto FOREIGN KEY (moto_id) REFERENCES MOTO(id)
);